-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.lugar
(
    id_lugar bigserial NOT NULL,
    departamento_o_estado character varying(255) COLLATE pg_catalog."default",
    nombre character varying(255) COLLATE pg_catalog."default",
    pais character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT lugar_pkey PRIMARY KEY (id_lugar),
    CONSTRAINT lugar_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.persona
(
    edad integer NOT NULL,
    id_lugar bigint,
    id_persona bigint NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default",
    ocupacion character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT persona_pkey PRIMARY KEY (id_persona)
);

ALTER TABLE IF EXISTS public.persona
    ADD CONSTRAINT fk61qepdi15hxi753ha4jkfcxqm FOREIGN KEY (id_lugar)
    REFERENCES public.lugar (id_lugar) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;